Update azure-static-web-apps-proud-sand-0a3911e10.yml

diff --git a/.github/workflows/azure-static-web-apps-proud-sand-0a3911e10.yml b/.github/workflows/azure-static-web-apps-proud-sand-0a3911e10.yml
--- a/.github/workflows/azure-static-web-apps-proud-sand-0a3911e10.yml
+++ b/.github/workflows/azure-static-web-apps-proud-sand-0a3911e10.yml
@@ -26,7 +26,7 @@ jobs:
       - name: Install dependencies
         run: npm install
       - name: Run build
-        run: npm run build || { echo "Build failed, check the logs for details."; cat /github/home/.npm/_logs/2024-12-11T09_25_28_323Z-debug-0.log; exit 1; }
+        run: npm run build || { echo "Build failed, check the logs for details."; cat /home/runner/work/_temp/_github_home/_logs/$(date +'%Y-%m-%dT%H_%M_%S_%Z')-debug-0.log; exit 1; }
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
